CREATE TABLE VENDAS(
    ID SERIAL PRIMARY KEY,
    DIA DATA,
    NUMERO_DE_PRODUTOS INT,
    VALOR_COMPRA FLOAT
);


CREATE PROCEDURE vendas_diarias (dia DATE)
SELECT NUMERO_DE_PRODUTOS AS NUMERO_DE_PRODUTOS
FROM VENDAS WHERE DIA = dia;
